project_id = "kpspzoooanlfpiuusian"

[functions.log-security-event]
verify_jwt = false

[functions.send-support-invitation]
verify_jwt = true

[functions.send-waitlist-confirmation]
verify_jwt = false

[functions.submit-call-request]
verify_jwt = false

[functions.validate-passcode]
verify_jwt = false
